version: '3'

services:
  webapp1:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./webapp1:/usr/share/nginx/html

  webapp2:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./webapp2:/usr/share/nginx/html
