# version: '3'

# services:
#   webapp1:
#     image: nginx:alpine
#     ports:
#       - "8080:80"
#     volumes:
#       - ./webapp1:/usr/share/nginx/html

#   webapp2:
#     image: nginx:alpine
#     ports:
#       - "8081:80"
#     volumes:
#       - ./webapp2:/usr/share/nginx/html

# mongodb:
#     image: mongo:latest
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db

# volumes:
#   mongodb_data:

version: '3.8'

services:
  webapp1:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./webapp1:/usr/share/nginx/html

  webapp2:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./webapp2:/usr/share/nginx/html

#   mongodb:
#     image: mongo
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db

# volumes:
#   mongodb_data:

phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8082:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example

volumes:
  db_data:
    driver: local